name: Deploy

on:
  push:
    branches:
      - main
      - feat/ci

jobs:
  build:
    name: Run remote ssh command
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            pwd
